# ============================================================
#   FoliaCustomCommands — config.yml
# ============================================================
#
# Muestra logs al registrar/desregistrar comandos (default: false)
verbose-outputs: false

# Recarga automáticamente los archivos de commands/ cuando detecta cambios (default: true)
auto-reload: true
