# ============================================================
#   ETCCore — config.yml
# ============================================================
# Configuración general del plugin.
#
# Configuraciones separadas por sistema:
#   - on-join.yml
#   - death-respawn.yml
#   - chat-format.yml
#   - blocked-commands.yml

verbose-outputs: false
auto-reload: true
update-checker: true
log-commands: false
build-protection: true
build-protection-message: "&cNecesitas ser aprobado para construir o romper bloques."
item-protection: true
item-protection-message: "&cNo puedes tirar objetos aquí."
mute-default-reason: "Violación de las normas del servidor"

# El formato del chat se configura en chat-format.yml
